language: node_js
sudo: true
node_js:
- 6.9.1
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts: github.com
before_install:
- bash ./.travis/checkout_secret.sh
script:
- gulp build
- gulp dist
- gulp release
branches:
  only:
  - dev
  - release
env:
  global:
    secure: e+fEH+g2yKj2ecRcRMja7yeOlEgOBFYcc4zawAuT26N+38yjq66xpd33nMDScmz9FWvgRV4KxESr3GRl3JjvP3+eWdNcwVUXKCZLwojE3XAq4uu5GsLNWwkOCi59IQIGw6o77vLGEAWbfm/Q8qoWL+K0L2uBL8BUYTrHkQ/0hIng2aQ2gMtlxA3M6/CpjaVQvrP1cOGNjb9Lnw1/cC16Ne1CkFSLRoIXaDaryPHd+sCMAUI6wJjgbz/pCBLUlsR90/PuShd+6fyZnqG2dllU65XplckJvlDDFUMxUmdigUtfL4BDPbXI8TE2DKJwlZp5WUSgrTy13Ua3o/0bm4K7+sNH2YZoUpNl5BmXFV+NFvhDOc9KMnxB8KXgMfyHNIJWgM8bWaEnGJ9hMfKW0k15SBIXIvoOR1+/gcw5xkDIPP5IqtbXeWptsliT6mFUWRpin1lIRzjZxNJJobMaznw7fwYIrX4aYsWB3udicq/z6w21cYJZQL7nHHgvAHqC+9HshGqdj2gaWX+fT+mgbjzyGypc7t3AbjzqiRN/3fQ5rI5qZOeZuqzvIkO5cgz6aXfQ8Lt4NFEgjV6TTjeQhWD4P6lTgxUA2JpLP1JeqPooHNFn/uZkkBdQxKis3I9UurlK4D6AlO42bHgaISBxq8+ySH7Hw27XjZ8YE6mGg7v7vRM=
