os: osx
language: node_js
sudo: true
node_js:
- 6.9.1
cache:
  apt: true
  directories:
  - node_modules
addons:
  ssh_known_hosts: github.com
before_install:
- openssl aes-256-cbc -K $encrypted_b3b18cd533be_key -iv $encrypted_b3b18cd533be_iv
  -in ./.travis/tb6_private_key.asc.enc -out ./.travis/tb6_private_key.asc -d
- brew update
- brew install git-secret
- gpg --import ./.travis/tb6_private_key.asc
script:
- git secret reveal
- yarn test
- yarn build
branches:
  only:
  - dev
  - release
env:
  global:
    secure: X5TC3fwQ/1shn1R9wY4Lm8Yvq3yqTjMcL14ZpjWzOrE1tDrgzeWWxD62a1/sKAxKMdylvi6Ho6uxXe9g3AfFWwK/5Nbf27QQvKTxx3rL+dYyd9ksfrpD36fv5Jg2dLpnnpXsOcz5ZXDcv46ozNc6ADBF4JZZyb0NF9/q+bDmciKZO4A6G5WZzQLPbruyBYqpBvwEYUyaajACCjY7eShwrkBrWguHiR0W5CSZThFA/652PO1AvyEr1VxmbaORh3Cnhtqd3ZMACJPQY2F3acQi45j5aP8M0LxMxijNuRIfXfyXF5xRjMci5bNHyjgFiqcABD87k8UkG1oJCNTZOqjGPbmWWE0za7OU+zDPFK5XfQIKDhtRHmEYjSzT+IU0kmPCJA9XJz+6p4HynVmBSj+wiPk1rvBqUOz+JIAh/rE9UaS+AcjCftpiIohnLcdU8EyBoxSWuNfrkse0PIprtjgIzSWc6ykTX8OJLtvvypm34+eRPUlZbheFgsPI45U0uFSQSOP4D/+ZUUYKJ5+eXaliHmNaAet/4eyE7fXn7CssZo4+1ia7FbT2kHcrPcu6RhaMX3mDgnHjNb/Xu6Ec1yyeTzPRucxMNx1k8mutJbhmuyCunyAhat3DPkAube3aLGSiuLSCn9+L07b5yi04/sPSMzbF+ZICyqmBHvfDJbyX8sA=
